### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by RedVortexDev**
Code is still needed for new text positions
whenimagininthesumma

### CODE REVIEW

**Comment by RedVortexDev** [comment]
also omg #1  !!

**Comment by Assassin-1234** [comment]
LGTM 👍

**Comment by Assassin-1234** [comment]
can you replace the cover image in the readme too? thanks.

**Review by face-hh — COMMENTED** [review]
Everything looks fine, will merge alongside the new coordinates for each image!

**Pull request merged**
