### PR TITLE
Redesigned Assets

### PR DESCRIPTION
**Pull request by arnav-kr**
TODO: Update Coordinate Mapping

### CODE REVIEW

**Comment by Iliannnn** [comment]
Great work. @Assassin-1234 or @face-hh can anyone of you update the coords?

**Comment by Assassin-1234** [comment]
I talked with face, I'll update the coords tomorrow and merge. Thank you for the PR!

**Comment by Iliannnn** [comment]
> I talked with face, I'll update the coords tomorrow and merge. Thank you for the PR!

Website will be there once the new designs are merged :)

**Comment by face-hh** [comment]
The coordinates have been changed to follow the new design, thank you @arnav-kr for your contribution 🎉

Also thanks to [the fix for having latest version for editly](https://github.com/Assassin-1234/discord-wrapped/pull/12)!

**Pull request merged**
